"""Regenerate the vendored stage tables. Run by hand, not at import time.

Two tables are shipped inside the package rather than fetched at runtime.

``ehdaa2.json`` -- EHDAA2 is inactive in OBO Foundry and frozen at
releases/2024-01-11. It is *not* obsolete: it is finished. A finished ontology
is the ideal pinned data dependency -- no version skew is possible -- and it is
also not loaded in Ubergraph, so there is no live structural route to it. It is
in OLS, but depending on an API's shape for a file that will never change buys
nothing.

``hsapdv.json`` -- small (260 terms) and active. Vendored for offline
determinism, stamped with the date it was built, and regenerated by this script.

Usage:  python tools/build_tables.py
"""

from __future__ import annotations

import json
import re
import sys
import urllib.request
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from ontomap.ubergraph import ONTOLOGY, Ubergraph, curie

DATA = Path(__file__).resolve().parents[1] / "src" / "ontomap" / "data"
EHDAA2_URL = "http://purl.obolibrary.org/obo/ehdaa2.obo"


def build_ehdaa2() -> dict:
    text = urllib.request.urlopen(EHDAA2_URL).read().decode("utf-8")
    version = re.search(r"^data-version: (.+)$", text, re.M)
    terms = {}
    for block in text.split("\n[Term]\n")[1:]:
        term_id = re.search(r"^id: (\S+)", block, re.M)
        if not term_id or not term_id.group(1).startswith("EHDAA2:"):
            continue
        name = re.search(r"^name: (.+)$", block, re.M)
        terms[term_id.group(1)] = {
            "name": name.group(1) if name else None,
            # starts_at / ends_at point straight at HsapDv stage terms, which is
            # what makes this the human staging route: UBERON --xref--> EHDAA2
            # --starts_at--> HsapDv --start_dpf--> a day.
            "starts_at": _first(block, "starts_at"),
            "ends_at": _first(block, "ends_at"),
            "develops_from": re.findall(r"^relationship: develops_from (\S+)", block, re.M),
        }
    return {
        "source": EHDAA2_URL,
        "data_version": version.group(1) if version else None,
        "built": date.today().isoformat(),
        "terms": terms,
    }


def _first(block: str, relation: str) -> str | None:
    found = re.findall(rf"^relationship: {relation} (\S+)", block, re.M)
    return found[0] if found else None


def build_hsapdv(ubergraph: Ubergraph) -> dict:
    rows = ubergraph.query(f"""
SELECT ?s ?p ?o WHERE {{
  GRAPH <{ONTOLOGY}> {{ ?s ?p ?o }}
  VALUES ?p {{ <http://www.w3.org/2000/01/rdf-schema#label>
              <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym>
              <http://www.geneontology.org/formats/oboInOwl#inSubset>
              <http://purl.obolibrary.org/obo/IAO_0000115>
              <http://purl.obolibrary.org/obo/hsapdv#start_dpf>
              <http://purl.obolibrary.org/obo/hsapdv#end_dpf> }}
  FILTER(STRSTARTS(STR(?s), "http://purl.obolibrary.org/obo/HsapDv_"))
}}""")
    terms: dict[str, dict] = {}
    for row in rows:
        term = terms.setdefault(
            curie(row["s"]),
            {
                "label": None,
                "definition": None,
                "synonyms": [],
                "start_dpf": None,
                "end_dpf": None,
                "granular": False,
            },
        )
        predicate, value = row["p"], row["o"]
        if predicate.endswith("#label"):
            term["label"] = value
        elif predicate.endswith("IAO_0000115"):
            term["definition"] = value
        elif predicate.endswith("hasExactSynonym"):
            term["synonyms"].append(value)
        elif predicate.endswith("start_dpf"):
            term["start_dpf"] = float(value)
        elif predicate.endswith("end_dpf"):
            term["end_dpf"] = float(value)
        elif predicate.endswith("inSubset") and value.endswith("granular_stage"):
            term["granular"] = True
    return {"source": "ubergraph", "built": date.today().isoformat(), "terms": terms}


if __name__ == "__main__":
    DATA.mkdir(parents=True, exist_ok=True)
    ehdaa2 = build_ehdaa2()
    (DATA / "ehdaa2.json").write_text(json.dumps(ehdaa2, indent=1, sort_keys=True))
    staged = sum(1 for t in ehdaa2["terms"].values() if t["starts_at"])
    print(f"ehdaa2.json: {len(ehdaa2['terms'])} terms, {staged} staged, {ehdaa2['data_version']}")

    hsapdv = build_hsapdv(Ubergraph())
    (DATA / "hsapdv.json").write_text(json.dumps(hsapdv, indent=1, sort_keys=True))
    windowed = sum(1 for t in hsapdv["terms"].values() if t["start_dpf"] is not None)
    print(f"hsapdv.json: {len(hsapdv['terms'])} terms, {windowed} with a day window")
